const Carta = require("./Carta")
const { CODIGO_TIPO_CARTA, NIVEL_EVOLUCION } = require("../utils/enums")
class CartaPokemon extends Carta {
    constructor(numero, nombre, ps, ataque, defensa, ataque_esp, defensa_esp, velocidad, suma, tipo_energia, cantidad_energia) {
        super(numero, nombre);
        this.pokemon = nombre;
        this.ps = ps;
        this.ataque = ataque;
        this.defensa = defensa;
        this.ataque_esp = ataque_esp;
        this.defensa_esp = defensa_esp;
        this.velocidad = velocidad;
        this.suma = suma;
        this.tipo_energia = tipo_energia;
        this.cantidad_energia = cantidad_energia;
    }

    getTipoEnergia() {
        return this.tipo_energia
    }
    getCantidadEnergia() {
        return this.cantidad_energia
    }

    static getCartaObject(payload) {
        const { numero, pokemon, ps, ataque, defensa, ataque_esp, defensa_esp, velocidad, suma, tipo_energia, cantidad_energia, disponible_en_tienda, oferta_en_tienda, precio } = payload
        return new CartaPokemon(numero, pokemon, ps, ataque, defensa, ataque_esp, defensa_esp, velocidad, suma, tipo_energia, cantidad_energia, disponible_en_tienda)
    }

    static getCartas() {
        return [
            CartaPokemon.getCartaObject({
                numero: "P1",
                pokemon: "Bulbasur",
                ps: "10",
                ataque: "10",
                defensa: "10",
                ataque_esp: "10",
                defensa_esp: "10",
                velocidad: "10",
                suma: "60",
                tipo_energia: CODIGO_TIPO_CARTA.HIERBA,
                cantidad_energia: NIVEL_EVOLUCION.BASICO,
                disponible_en_tienda: false,
                oferta_en_tienda: false,
                precio: 100
            }),
            CartaPokemon.getCartaObject({
                numero: "P2",
                pokemon: "Ivysaur",
                ps: "10",
                ataque: "10",
                defensa: "10",
                ataque_esp: "10",
                defensa_esp: "10",
                velocidad: "10",
                suma: "60",
                tipo_energia: CODIGO_TIPO_CARTA.HIERBA,
                cantidad_energia: NIVEL_EVOLUCION.ETAPA_1,
                disponible_en_tienda: false,
                oferta_en_tienda: false,
                precio: 100
            }),
            CartaPokemon.getCartaObject({
                numero: "P3",
                pokemon: "Venusaur",
                ps: "10",
                ataque: "10",
                defensa: "10",
                ataque_esp: "10",
                defensa_esp: "10",
                velocidad: "10",
                suma: "60",
                tipo_energia: CODIGO_TIPO_CARTA.HIERBA,
                cantidad_energia: NIVEL_EVOLUCION.ETAPA_1,
                disponible_en_tienda: false,
                oferta_en_tienda: false,
                precio: 100

            }),
            CartaPokemon.getCartaObject({
                numero: "P4",
                pokemon: "Charmander",
                ps: "10",
                ataque: "10",
                defensa: "10",
                ataque_esp: "10",
                defensa_esp: "10",
                velocidad: "10",
                suma: "60",
                tipo_energia: CODIGO_TIPO_CARTA.FUEGO,
                cantidad_energia: NIVEL_EVOLUCION.BASICO,
                disponible_en_tienda: false,
                oferta_en_tienda: false,
                precio: 100
            }),
            CartaPokemon.getCartaObject({
                numero: "P5",
                pokemon: "Charmaleon",
                ps: "10",
                ataque: "10",
                defensa: "10",
                ataque_esp: "10",
                defensa_esp: "10",
                velocidad: "10",
                suma: "60",
                tipo_energia: CODIGO_TIPO_CARTA.FUEGO,
                cantidad_energia: NIVEL_EVOLUCION.ETAPA_1,
                disponible_en_tienda: false,
                oferta_en_tienda: false,
                precio: 100
            }),
            CartaPokemon.getCartaObject({
                numero: "P6",
                pokemon: "Charizard",
                ps: "10",
                ataque: "10",
                defensa: "10",
                ataque_esp: "10",
                defensa_esp: "10",
                velocidad: "10",
                suma: "60",
                tipo_energia: CODIGO_TIPO_CARTA.FUEGO,
                cantidad_energia: NIVEL_EVOLUCION.ETAPA_1,
                disponible_en_tienda: false,
                oferta_en_tienda: false,
                precio: 100
            }),
            CartaPokemon.getCartaObject({
                numero: "P7",
                pokemon: "Squirtle",
                ps: "10",
                ataque: "10",
                defensa: "10",
                ataque_esp: "10",
                defensa_esp: "10",
                velocidad: "10",
                suma: "60",
                tipo_energia: CODIGO_TIPO_CARTA.AGUA,
                cantidad_energia: NIVEL_EVOLUCION.BASICO,
                disponible_en_tienda: false,
                oferta_en_tienda: false,
                precio: 100
            }),
            CartaPokemon.getCartaObject({
                numero: "P8",
                pokemon: "Wartortle",
                ps: "10",
                ataque: "10",
                defensa: "10",
                ataque_esp: "10",
                defensa_esp: "10",
                velocidad: "10",
                suma: "60",
                tipo_energia: CODIGO_TIPO_CARTA.AGUA,
                cantidad_energia: NIVEL_EVOLUCION.ETAPA_1,
                disponible_en_tienda: false,
                oferta_en_tienda: false,
                precio: 100
            }),
            CartaPokemon.getCartaObject({
                numero: "P9",
                pokemon: "Blastoise",
                ps: "10",
                ataque: "10",
                defensa: "10",
                ataque_esp: "10",
                defensa_esp: "10",
                velocidad: "10",
                suma: "60",
                tipo_energia: CODIGO_TIPO_CARTA.AGUA,
                cantidad_energia: NIVEL_EVOLUCION.ETAPA_1,
                disponible_en_tienda: false,
                oferta_en_tienda: false,
                precio: 100
            }),
            CartaPokemon.getCartaObject({
                numero: "P10",
                pokemon: "Caterpie",
                ps: "10",
                ataque: "10",
                defensa: "10",
                ataque_esp: "10",
                defensa_esp: "10",
                velocidad: "10",
                suma: "60",
                tipo_energia: CODIGO_TIPO_CARTA.HIERBA,
                cantidad_energia: NIVEL_EVOLUCION.BASICO,
                disponible_en_tienda: false,
                oferta_en_tienda: false,
                precio: 100
            }),
            CartaPokemon.getCartaObject({
                numero: "P11",
                pokemon: "Metapod",
                ps: "10",
                ataque: "10",
                defensa: "10",
                ataque_esp: "10",
                defensa_esp: "10",
                velocidad: "10",
                suma: "60",
                tipo_energia: CODIGO_TIPO_CARTA.HIERBA,
                cantidad_energia: NIVEL_EVOLUCION.ETAPA_1,
                disponible_en_tienda: false,
                oferta_en_tienda: false,
                precio: 100
            }),
            CartaPokemon.getCartaObject({
                numero: "P12",
                pokemon: "Butterfree",
                ps: "10",
                ataque: "10",
                defensa: "10",
                ataque_esp: "10",
                defensa_esp: "10",
                velocidad: "10",
                suma: "60",
                tipo_energia: CODIGO_TIPO_CARTA.HIERBA,
                cantidad_energia: NIVEL_EVOLUCION.ETAPA_1,
                disponible_en_tienda: false,
                oferta_en_tienda: false,
                precio: 100
            }),
            CartaPokemon.getCartaObject({
                numero: "P13",
                pokemon: "Weedle",
                ps: "10",
                ataque: "10",
                defensa: "10",
                ataque_esp: "10",
                defensa_esp: "10",
                velocidad: "10",
                suma: "60",
                tipo_energia: CODIGO_TIPO_CARTA.HIERBA,
                cantidad_energia: NIVEL_EVOLUCION.BASICO,
                disponible_en_tienda: false,
                oferta_en_tienda: false,
                precio: 100
            }),
            CartaPokemon.getCartaObject({
                numero: "P14",
                pokemon: "Kakuna",
                ps: "10",
                ataque: "10",
                defensa: "10",
                ataque_esp: "10",
                defensa_esp: "10",
                velocidad: "10",
                suma: "60",
                tipo_energia: CODIGO_TIPO_CARTA.HIERBA,
                cantidad_energia: NIVEL_EVOLUCION.ETAPA_1,
                disponible_en_tienda: false,
                oferta_en_tienda: false,
                precio: 100
            }),
            CartaPokemon.getCartaObject({
                numero: "P15",
                pokemon: "Beedrill",
                ps: "10",
                ataque: "10",
                defensa: "10",
                ataque_esp: "10",
                defensa_esp: "10",
                velocidad: "10",
                suma: "60",
                tipo_energia: CODIGO_TIPO_CARTA.HIERBA,
                cantidad_energia: NIVEL_EVOLUCION.ETAPA_1,
                disponible_en_tienda: false,
                oferta_en_tienda: false,
                precio: 100
            }),
            CartaPokemon.getCartaObject({
                numero: "P16",
                pokemon: "Pidgey",
                ps: "10",
                ataque: "10",
                defensa: "10",
                ataque_esp: "10",
                defensa_esp: "10",
                velocidad: "10",
                suma: "60",
                tipo_energia: CODIGO_TIPO_CARTA.INCOLORO,
                cantidad_energia: NIVEL_EVOLUCION.BASICO,
                disponible_en_tienda: false,
                oferta_en_tienda: false,
                precio: 100
            }),
            CartaPokemon.getCartaObject({
                numero: "P17",
                pokemon: "Pidgeotto",
                ps: "10",
                ataque: "10",
                defensa: "10",
                ataque_esp: "10",
                defensa_esp: "10",
                velocidad: "10",
                suma: "60",
                tipo_energia: CODIGO_TIPO_CARTA.INCOLORO,
                cantidad_energia: NIVEL_EVOLUCION.ETAPA_1,
                disponible_en_tienda: false,
                oferta_en_tienda: false,
                precio: 100
            }),
            CartaPokemon.getCartaObject({
                numero: "P18",
                pokemon: "Pidgeot",
                ps: "10",
                ataque: "10",
                defensa: "10",
                ataque_esp: "10",
                defensa_esp: "10",
                velocidad: "10",
                suma: "60",
                tipo_energia: CODIGO_TIPO_CARTA.INCOLORO,
                cantidad_energia: NIVEL_EVOLUCION.ETAPA_1,
                disponible_en_tienda: false,
                oferta_en_tienda: false,
                precio: 100
            }),
            CartaPokemon.getCartaObject({
                numero: "P19",
                pokemon: "Rattata",
                ps: "10",
                ataque: "10",
                defensa: "10",
                ataque_esp: "10",
                defensa_esp: "10",
                velocidad: "10",
                suma: "60",
                tipo_energia: CODIGO_TIPO_CARTA.INCOLORO,
                cantidad_energia: NIVEL_EVOLUCION.BASICO,
                disponible_en_tienda: false,
                oferta_en_tienda: false,
                precio: 100
            }),
            CartaPokemon.getCartaObject({
                numero: "P20",
                pokemon: "Raticate",
                ps: "10",
                ataque: "10",
                defensa: "10",
                ataque_esp: "10",
                defensa_esp: "10",
                velocidad: "10",
                suma: "60",
                tipo_energia: CODIGO_TIPO_CARTA.INCOLORO,
                cantidad_energia: NIVEL_EVOLUCION.ETAPA_1,
                disponible_en_tienda: false,
                oferta_en_tienda: false,
                precio: 100
            }),
            CartaPokemon.getCartaObject({
                numero: "P21",
                pokemon: "Spearow",
                ps: "10",
                ataque: "10",
                defensa: "10",
                ataque_esp: "10",
                defensa_esp: "10",
                velocidad: "10",
                suma: "60",
                tipo_energia: CODIGO_TIPO_CARTA.INCOLORO,
                cantidad_energia: NIVEL_EVOLUCION.BASICO,
                disponible_en_tienda: false,
                oferta_en_tienda: false,
                precio: 100
            }),
            CartaPokemon.getCartaObject({
                numero: "P22",
                pokemon: "Fearow",
                ps: "10",
                ataque: "10",
                defensa: "10",
                ataque_esp: "10",
                defensa_esp: "10",
                velocidad: "10",
                suma: "60",
                tipo_energia: CODIGO_TIPO_CARTA.INCOLORO,
                cantidad_energia: NIVEL_EVOLUCION.ETAPA_1,
                disponible_en_tienda: false,
                oferta_en_tienda: false,
                precio: 100
            }),
            CartaPokemon.getCartaObject({
                numero: "P23",
                pokemon: "Ekans",
                ps: "10",
                ataque: "10",
                defensa: "10",
                ataque_esp: "10",
                defensa_esp: "10",
                velocidad: "10",
                suma: "60",
                tipo_energia: CODIGO_TIPO_CARTA.HIERBA,
                cantidad_energia: NIVEL_EVOLUCION.BASICO,
                disponible_en_tienda: false,
                oferta_en_tienda: false,
                precio: 100
            }),
            CartaPokemon.getCartaObject({
                numero: "P24",
                pokemon: "Arbok",
                ps: "10",
                ataque: "10",
                defensa: "10",
                ataque_esp: "10",
                defensa_esp: "10",
                velocidad: "10",
                suma: "60",
                tipo_energia: CODIGO_TIPO_CARTA.HIERBA,
                cantidad_energia: NIVEL_EVOLUCION.ETAPA_1,
                disponible_en_tienda: false,
                oferta_en_tienda: false,
                precio: 100
            }),
            CartaPokemon.getCartaObject({
                numero: "P25",
                pokemon: "Pikachu",
                ps: "10",
                ataque: "10",
                defensa: "10",
                ataque_esp: "10",
                defensa_esp: "10",
                velocidad: "10",
                suma: "60",
                tipo_energia: CODIGO_TIPO_CARTA.RAYO,
                cantidad_energia: NIVEL_EVOLUCION.BASICO,
                disponible_en_tienda: false,
                oferta_en_tienda: false,
                precio: 100
            }),
            CartaPokemon.getCartaObject({
                numero: "P26",
                pokemon: "Raichu",
                ps: "10",
                ataque: "10",
                defensa: "10",
                ataque_esp: "10",
                defensa_esp: "10",
                velocidad: "10",
                suma: "60",
                tipo_energia: CODIGO_TIPO_CARTA.RAYO,
                cantidad_energia: NIVEL_EVOLUCION.ETAPA_1,
                disponible_en_tienda: false,
                oferta_en_tienda: false,
                precio: 100
            }),
            CartaPokemon.getCartaObject({
                numero: "P27",
                pokemon: "Sandshrew",
                ps: "10",
                ataque: "10",
                defensa: "10",
                ataque_esp: "10",
                defensa_esp: "10",
                velocidad: "10",
                suma: "60",
                tipo_energia: CODIGO_TIPO_CARTA.TIERRA,
                cantidad_energia: NIVEL_EVOLUCION.BASICO,
                disponible_en_tienda: false,
                oferta_en_tienda: false,
                precio: 100
            }),
            CartaPokemon.getCartaObject({
                numero: "P28",
                pokemon: "Sandslash",
                ps: "10",
                ataque: "10",
                defensa: "10",
                ataque_esp: "10",
                defensa_esp: "10",
                velocidad: "10",
                suma: "60",
                tipo_energia: CODIGO_TIPO_CARTA.TIERRA,
                cantidad_energia: NIVEL_EVOLUCION.ETAPA_1,
                disponible_en_tienda: false,
                oferta_en_tienda: false,
                precio: 100
            }),
            CartaPokemon.getCartaObject({
                numero: "P29",
                pokemon: "Nidoran",
                ps: "10",
                ataque: "10",
                defensa: "10",
                ataque_esp: "10",
                defensa_esp: "10",
                velocidad: "10",
                suma: "60",
                tipo_energia: CODIGO_TIPO_CARTA.HIERBA,
                cantidad_energia: NIVEL_EVOLUCION.BASICO,
                disponible_en_tienda: false,
                oferta_en_tienda: false,
                precio: 100
            }),
            CartaPokemon.getCartaObject({
                numero: "P30",
                pokemon: "Nidorina",
                ps: "10",
                ataque: "10",
                defensa: "10",
                ataque_esp: "10",
                defensa_esp: "10",
                velocidad: "10",
                suma: "60",
                tipo_energia: CODIGO_TIPO_CARTA.HIERBA,
                cantidad_energia: NIVEL_EVOLUCION.ETAPA_1,
                disponible_en_tienda: false,
                oferta_en_tienda: false,
                precio: 100
            }),
            CartaPokemon.getCartaObject({
                numero: "P31",
                pokemon: "Nidoqueen",
                ps: "10",
                ataque: "10",
                defensa: "10",
                ataque_esp: "10",
                defensa_esp: "10",
                velocidad: "10",
                suma: "60",
                tipo_energia: CODIGO_TIPO_CARTA.HIERBA,
                cantidad_energia: NIVEL_EVOLUCION.ETAPA_1,
                disponible_en_tienda: false,
                oferta_en_tienda: false,
                precio: 100
            }),
            CartaPokemon.getCartaObject({
                numero: "P32",
                pokemon: "Nidoran",
                ps: "10",
                ataque: "10",
                defensa: "10",
                ataque_esp: "10",
                defensa_esp: "10",
                velocidad: "10",
                suma: "60",
                tipo_energia: CODIGO_TIPO_CARTA.HIERBA,
                cantidad_energia: NIVEL_EVOLUCION.BASICO,
                disponible_en_tienda: false,
                oferta_en_tienda: false,
                precio: 100
            }),
            CartaPokemon.getCartaObject({
                numero: "P33",
                pokemon: "Nidorino",
                ps: "10",
                ataque: "10",
                defensa: "10",
                ataque_esp: "10",
                defensa_esp: "10",
                velocidad: "10",
                suma: "60",
                tipo_energia: CODIGO_TIPO_CARTA.HIERBA,
                cantidad_energia: NIVEL_EVOLUCION.ETAPA_1,
                disponible_en_tienda: false,
                oferta_en_tienda: false,
                precio: 100
            }),
            CartaPokemon.getCartaObject({
                numero: "P34",
                pokemon: "Nidoking",
                ps: "10",
                ataque: "10",
                defensa: "10",
                ataque_esp: "10",
                defensa_esp: "10",
                velocidad: "10",
                suma: "60",
                tipo_energia: CODIGO_TIPO_CARTA.HIERBA,
                cantidad_energia: NIVEL_EVOLUCION.ETAPA_1,
                disponible_en_tienda: false,
                oferta_en_tienda: false,
                precio: 100
            }),
        ]
    }

    static getPikachuToken(){
        return true
    }

    static getMeowthToken(){
        return false
    }
}

module.exports = CartaPokemon