const CODIGO_TIPO_CARTA = require('../utils/enums').CODIGO_TIPO_CARTA
const NIVEL_EVOLUCION = require('../utils/enums').NIVEL_EVOLUCION

const cartasPokemon = [
    {
        numero: "P1",   
        pokemon: "Bulbasur",
        ps: "10",
        ataque: "10",
        defensa: "10",
        ataque_esp: "10",
        defensa_esp: "10",
        velocidad: "10",
        suma: "60",
        tipo_energia: CODIGO_TIPO_CARTA.HIERBA,
        cantidad_energia: NIVEL_EVOLUCION.BASICO,
        disponible_en_tienda: false,
        oferta_en_tienda: false,
        precio: 100
    },
    {
        numero: "P2",   
        pokemon: "Ivysaur",
        ps: "10",
        ataque: "10",
        defensa: "10",
        ataque_esp: "10",
        defensa_esp: "10",
        velocidad: "10",
        suma: "60",
        tipo_energia: CODIGO_TIPO_CARTA.HIERBA,
        cantidad_energia: NIVEL_EVOLUCION.ETAPA_1,
        disponible_en_tienda: false,
        oferta_en_tienda: false,
        precio: 100
    },
    {
        numero: "P3",   
        pokemon: "Venusaur",
        ps: "10",
        ataque: "10",
        defensa: "10",
        ataque_esp: "10",
        defensa_esp: "10",
        velocidad: "10",
        suma: "60",
        tipo_energia: CODIGO_TIPO_CARTA.HIERBA,
        cantidad_energia: NIVEL_EVOLUCION.ETAPA_1,
        disponible_en_tienda: false,
        oferta_en_tienda: false,
        precio: 100

    },
    {
        numero: "P4",   
        pokemon: "Charmander",
        ps: "10",
        ataque: "10",
        defensa: "10",
        ataque_esp: "10",
        defensa_esp: "10",
        velocidad: "10",
        suma: "60",
        tipo_energia: CODIGO_TIPO_CARTA.FUEGO,
        cantidad_energia: NIVEL_EVOLUCION.BASICO,
        disponible_en_tienda: false,
        oferta_en_tienda: false,
        precio: 100
    },
    {
        numero: "P5",   
        pokemon: "Charmaleon",
        ps: "10",
        ataque: "10",
        defensa: "10",
        ataque_esp: "10",
        defensa_esp: "10",
        velocidad: "10",
        suma: "60",
        tipo_energia: CODIGO_TIPO_CARTA.FUEGO,
        cantidad_energia: NIVEL_EVOLUCION.ETAPA_1,
        disponible_en_tienda: false,
        oferta_en_tienda: false,
        precio: 100
    },
    {
        numero: "P6",   
        pokemon: "Charizard",
        ps: "10",
        ataque: "10",
        defensa: "10",
        ataque_esp: "10",
        defensa_esp: "10",
        velocidad: "10",
        suma: "60",
        tipo_energia: CODIGO_TIPO_CARTA.FUEGO,
        cantidad_energia: NIVEL_EVOLUCION.ETAPA_1,
        disponible_en_tienda: false,
        oferta_en_tienda: false,
        precio: 100
    },
    {
        numero: "P7",   
        pokemon: "Squirtle",
        ps: "10",
        ataque: "10",
        defensa: "10",
        ataque_esp: "10",
        defensa_esp: "10",
        velocidad: "10",
        suma: "60",
        tipo_energia: CODIGO_TIPO_CARTA.AGUA,
        cantidad_energia: NIVEL_EVOLUCION.BASICO,
        disponible_en_tienda: false,
        oferta_en_tienda: false,
        precio: 100
    },
    {
        numero: "P8",   
        pokemon: "Wartortle",
        ps: "10",
        ataque: "10",
        defensa: "10",
        ataque_esp: "10",
        defensa_esp: "10",
        velocidad: "10",
        suma: "60",
        tipo_energia: CODIGO_TIPO_CARTA.AGUA,
        cantidad_energia: NIVEL_EVOLUCION.ETAPA_1,
        disponible_en_tienda: false,
        oferta_en_tienda: false,
        precio: 100
    },
    {
        numero: "P9",   
        pokemon: "Blastoise",
        ps: "10",
        ataque: "10",
        defensa: "10",
        ataque_esp: "10",
        defensa_esp: "10",
        velocidad: "10",
        suma: "60",        
        tipo_energia: CODIGO_TIPO_CARTA.AGUA,
        cantidad_energia: NIVEL_EVOLUCION.ETAPA_1,
        disponible_en_tienda: false,
        oferta_en_tienda: false,
        precio: 100
    },
    {
        numero: "P10",   
        pokemon: "Caterpie",
        ps: "10",
        ataque: "10",
        defensa: "10",
        ataque_esp: "10",
        defensa_esp: "10",
        velocidad: "10",
        suma: "60",
        tipo_energia: CODIGO_TIPO_CARTA.HIERBA,
        cantidad_energia: NIVEL_EVOLUCION.BASICO,
        disponible_en_tienda: false,
        oferta_en_tienda: false,
        precio: 100
    },
    {
        numero: "P11",   
        pokemon: "Metapod",
        ps: "10",
        ataque: "10",
        defensa: "10",
        ataque_esp: "10",
        defensa_esp: "10",
        velocidad: "10",
        suma: "60",
        tipo_energia: CODIGO_TIPO_CARTA.HIERBA,
        cantidad_energia: NIVEL_EVOLUCION.ETAPA_1,
        disponible_en_tienda: false,
        oferta_en_tienda: false,
        precio: 100
    },
    {
        numero: "P12",   
        pokemon: "Butterfree",
        ps: "10",
        ataque: "10",
        defensa: "10",
        ataque_esp: "10",
        defensa_esp: "10",
        velocidad: "10",
        suma: "60",
        tipo_energia: CODIGO_TIPO_CARTA.HIERBA,
        cantidad_energia: NIVEL_EVOLUCION.ETAPA_1,
        disponible_en_tienda: false,
        oferta_en_tienda: false,
        precio: 100
    },
    {
        numero: "P13",   
        pokemon: "Weedle",
        ps: "10",
        ataque: "10",
        defensa: "10",
        ataque_esp: "10",
        defensa_esp: "10",
        velocidad: "10",
        suma: "60",
        tipo_energia: CODIGO_TIPO_CARTA.HIERBA,
        cantidad_energia: NIVEL_EVOLUCION.BASICO,
        disponible_en_tienda: false,
        oferta_en_tienda: false,
        precio: 100
    },
    {
        numero: "P14",   
        pokemon: "Kakuna",
        ps: "10",
        ataque: "10",
        defensa: "10",
        ataque_esp: "10",
        defensa_esp: "10",
        velocidad: "10",
        suma: "60",
        tipo_energia: CODIGO_TIPO_CARTA.HIERBA,
        cantidad_energia: NIVEL_EVOLUCION.ETAPA_1,
        disponible_en_tienda: false,
        oferta_en_tienda: false,
        precio: 100
    },
    {
        numero: "P15",   
        pokemon: "Beedrill",
        ps: "10",
        ataque: "10",
        defensa: "10",
        ataque_esp: "10",
        defensa_esp: "10",
        velocidad: "10",
        suma: "60",
        tipo_energia: CODIGO_TIPO_CARTA.HIERBA,
        cantidad_energia: NIVEL_EVOLUCION.ETAPA_1,
        disponible_en_tienda: false,
        oferta_en_tienda: false,
        precio: 100
    },
    {
        numero: "P16",   
        pokemon: "Pidgey",
        ps: "10",
        ataque: "10",
        defensa: "10",
        ataque_esp: "10",
        defensa_esp: "10",
        velocidad: "10",
        suma: "60",
        tipo_energia: CODIGO_TIPO_CARTA.INCOLORO,
        cantidad_energia: NIVEL_EVOLUCION.BASICO,
        disponible_en_tienda: false,
        oferta_en_tienda: false,
        precio: 100
    },
    {
        numero: "P17",   
        pokemon: "Pidgeotto",
        ps: "10",
        ataque: "10",
        defensa: "10",
        ataque_esp: "10",
        defensa_esp: "10",
        velocidad: "10",
        suma: "60",
        tipo_energia: CODIGO_TIPO_CARTA.INCOLORO,
        cantidad_energia: NIVEL_EVOLUCION.ETAPA_1,
        disponible_en_tienda: false,
        oferta_en_tienda: false,
        precio: 100
    },
    {
        numero: "P18",   
        pokemon: "Pidgeot",
        ps: "10",
        ataque: "10",
        defensa: "10",
        ataque_esp: "10",
        defensa_esp: "10",
        velocidad: "10",
        suma: "60",
        tipo_energia: CODIGO_TIPO_CARTA.INCOLORO,
        cantidad_energia: NIVEL_EVOLUCION.ETAPA_1,
        disponible_en_tienda: false,
        oferta_en_tienda: false,
        precio: 100
    },
    {
        numero: "P19",   
        pokemon: "Rattata",
        ps: "10",
        ataque: "10",
        defensa: "10",
        ataque_esp: "10",
        defensa_esp: "10",
        velocidad: "10",
        suma: "60",
        tipo_energia: CODIGO_TIPO_CARTA.INCOLORO,
        cantidad_energia: NIVEL_EVOLUCION.BASICO,
        disponible_en_tienda: false,
        oferta_en_tienda: false,
        precio: 100
    },
    {
        numero: "P20",   
        pokemon: "Raticate",
        ps: "10",
        ataque: "10",
        defensa: "10",
        ataque_esp: "10",
        defensa_esp: "10",
        velocidad: "10",
        suma: "60",
        tipo_energia: CODIGO_TIPO_CARTA.INCOLORO,
        cantidad_energia: NIVEL_EVOLUCION.ETAPA_1,
        disponible_en_tienda: false,
        oferta_en_tienda: false,
        precio: 100
    },
    {
        numero: "P21",   
        pokemon: "Spearow",
        ps: "10",
        ataque: "10",
        defensa: "10",
        ataque_esp: "10",
        defensa_esp: "10",
        velocidad: "10",
        suma: "60",
        tipo_energia: CODIGO_TIPO_CARTA.INCOLORO,
        cantidad_energia: NIVEL_EVOLUCION.BASICO,
        disponible_en_tienda: false,
        oferta_en_tienda: false,
        precio: 100
    },
    {
        numero: "P22",   
        pokemon: "Fearow",
        ps: "10",
        ataque: "10",
        defensa: "10",
        ataque_esp: "10",
        defensa_esp: "10",
        velocidad: "10",
        suma: "60",
        tipo_energia: CODIGO_TIPO_CARTA.INCOLORO,
        cantidad_energia: NIVEL_EVOLUCION.ETAPA_1,
        disponible_en_tienda: false,
        oferta_en_tienda: false,
        precio: 100
    },
    {
        numero: "P23",   
        pokemon: "Ekans",
        ps: "10",
        ataque: "10",
        defensa: "10",
        ataque_esp: "10",
        defensa_esp: "10",
        velocidad: "10",
        suma: "60",
        tipo_energia: CODIGO_TIPO_CARTA.HIERBA,
        cantidad_energia: NIVEL_EVOLUCION.BASICO,
        disponible_en_tienda: false,
        oferta_en_tienda: false,
        precio: 100
    },
    {
        numero: "P24",   
        pokemon: "Arbok",
        ps: "10",
        ataque: "10",
        defensa: "10",
        ataque_esp: "10",
        defensa_esp: "10",
        velocidad: "10",
        suma: "60",
        tipo_energia: CODIGO_TIPO_CARTA.HIERBA,
        cantidad_energia: NIVEL_EVOLUCION.ETAPA_1,
        disponible_en_tienda: false,
        oferta_en_tienda: false,
        precio: 100
    },
    {
        numero: "P25",   
        pokemon: "Pikachu",
        ps: "10",
        ataque: "10",
        defensa: "10",
        ataque_esp: "10",
        defensa_esp: "10",
        velocidad: "10",
        suma: "60",
        tipo_energia: CODIGO_TIPO_CARTA.RAYO,
        cantidad_energia: NIVEL_EVOLUCION.BASICO,
        disponible_en_tienda: false,
        oferta_en_tienda: false,
        precio: 100
    },
    {
        numero: "P26",   
        pokemon: "Raichu",
        ps: "10",
        ataque: "10",
        defensa: "10",
        ataque_esp: "10",
        defensa_esp: "10",
        velocidad: "10",
        suma: "60",
        tipo_energia: CODIGO_TIPO_CARTA.RAYO,
        cantidad_energia: NIVEL_EVOLUCION.ETAPA_1,
        disponible_en_tienda: false,
        oferta_en_tienda: false,
        precio: 100
    },
    {
        numero: "P27",   
        pokemon: "Sandshrew",
        ps: "10",
        ataque: "10",
        defensa: "10",
        ataque_esp: "10",
        defensa_esp: "10",
        velocidad: "10",
        suma: "60",
        tipo_energia: CODIGO_TIPO_CARTA.TIERRA,
        cantidad_energia: NIVEL_EVOLUCION.BASICO,
        disponible_en_tienda: false,
        oferta_en_tienda: false,
        precio: 100
    },
    {
        numero: "P28",   
        pokemon: "Sandslash",
        ps: "10",
        ataque: "10",
        defensa: "10",
        ataque_esp: "10",
        defensa_esp: "10",
        velocidad: "10",
        suma: "60",
        tipo_energia: CODIGO_TIPO_CARTA.TIERRA,
        cantidad_energia: NIVEL_EVOLUCION.ETAPA_1,
        disponible_en_tienda: false,
        oferta_en_tienda: false,
        precio: 100
    },
    {
        numero: "P29",   
        pokemon: "Nidoran",
        ps: "10",
        ataque: "10",
        defensa: "10",
        ataque_esp: "10",
        defensa_esp: "10",
        velocidad: "10",
        suma: "60",
        tipo_energia: CODIGO_TIPO_CARTA.HIERBA,
        cantidad_energia: NIVEL_EVOLUCION.BASICO,
        disponible_en_tienda: false,
        oferta_en_tienda: false,
        precio: 100
    },
    {
        numero: "P30",   
        pokemon: "Nidorina",
        ps: "10",
        ataque: "10",
        defensa: "10",
        ataque_esp: "10",
        defensa_esp: "10",
        velocidad: "10",
        suma: "60",
        tipo_energia: CODIGO_TIPO_CARTA.HIERBA,
        cantidad_energia: NIVEL_EVOLUCION.ETAPA_1,
        disponible_en_tienda: false,
        oferta_en_tienda: false,
        precio: 100
    },
    {
        numero: "P31",   
        pokemon: "Nidoqueen",
        ps: "10",
        ataque: "10",
        defensa: "10",
        ataque_esp: "10",
        defensa_esp: "10",
        velocidad: "10",
        suma: "60",
        tipo_energia: CODIGO_TIPO_CARTA.HIERBA,
        cantidad_energia: NIVEL_EVOLUCION.ETAPA_1,
        disponible_en_tienda: false,
        oferta_en_tienda: false,
        precio: 100
    },
    {
        numero: "P32",   
        pokemon: "Nidoran",
        ps: "10",
        ataque: "10",
        defensa: "10",
        ataque_esp: "10",
        defensa_esp: "10",
        velocidad: "10",
        suma: "60",
        tipo_energia: CODIGO_TIPO_CARTA.HIERBA,
        cantidad_energia: NIVEL_EVOLUCION.BASICO,
        disponible_en_tienda: false,
        oferta_en_tienda: false,
        precio: 100
    },
    {
        numero: "P33",   
        pokemon: "Nidorino",
        ps: "10",
        ataque: "10",
        defensa: "10",
        ataque_esp: "10",
        defensa_esp: "10",
        velocidad: "10",
        suma: "60",
        tipo_energia: CODIGO_TIPO_CARTA.HIERBA,
        cantidad_energia: NIVEL_EVOLUCION.ETAPA_1,
        disponible_en_tienda: false,
        oferta_en_tienda: false,
        precio: 100
    },
    {
        numero: "P34",   
        pokemon: "Nidoking",
        ps: "10",
        ataque: "10",
        defensa: "10",
        ataque_esp: "10",
        defensa_esp: "10",
        velocidad: "10",
        suma: "60",
        tipo_energia: CODIGO_TIPO_CARTA.HIERBA,
        cantidad_energia: NIVEL_EVOLUCION.ETAPA_1,
        disponible_en_tienda: false,
        oferta_en_tienda: false,
        precio: 100
    },
]

module.exports = cartasPokemon